package net.mcsm.extras.client;

import net.minecraft.util.Mth;

/**
 * BUILD #430 -- THE BACKDROP PALETTE. THE SUPPLIED SHEETS' COLOURS, IN ONE PLACE.
 *
 * <p>Both backdrop renderers used to carry their own hand-typed ramps: the
 * world-attached atmosphere wall ({@link McsmAtmosphericMeshComponent}) and the
 * story stage shell ({@link McsmExperimentalStoryStage}). Two hand-typed ramps
 * is one ramp too many. They disagreed with each other and with the three
 * supplied sheets, and nothing in the build could notice, because the sky
 * shader's columns are traced and parity-checked while the backdrops were not.
 * That is what "the colours haven't really changed at all" and "backdrops still
 * not the accurate colours" were looking at.
 *
 * <p>The stop block below is generated by {@code ci/sync_backdrop_palette.py}
 * out of {@code ci/palette_tables.py}, i.e. out of the SAME traced stop tables
 * the shipped sky wears, expanded from the supplied sheets. {@code --check}
 * fails the build if a single stop, a single routing boundary or the
 * interpolation itself ever stops matching them. Both renderers then read
 * {@link #column(float, float)} and keep no colour of their own.
 *
 * <p>{@code t} runs the way the sheets do: {@code t = 0} is the zenith (their
 * top row), {@code t = 1} is the horizon (their bottom row). The routing pairs
 * are sky.fsh's own, so the wall changes band at the same instant the sky does.
 */
public final class McsmBackdropPalette {

    /** Six stops per sheet: zenith, three quarters, middle, quarter, near horizon, horizon. */
    public static final int STOPS = 6;

    /** The near-black the atmosphere wall fades to along its lower edge. */
    public static final int VOID_BLACK = 0x010308;

    // MCSM_BACKDROP_PALETTE_BEGIN -- generated by ci/sync_backdrop_palette.py; do not hand-edit.
    // Source: ci/palette_tables.py, i.e. the stop tables the shipped sky wears,
    // expanded from the three supplied sheets. Stops run zenith -> horizon.
    public static final int[] TEAL = {0x0C1216, 0x0D1317, 0x0E1418, 0x0E151A, 0x0F161B, 0x10171C, 0x10181D, 0x11191E, 0x121A1F, 0x121B20, 0x131C22, 0x141D23, 0x141E24, 0x151F25, 0x162026, 0x172128, 0x172228, 0x182329, 0x18242A, 0x19252B, 0x1A252C, 0x1A262C, 0x1B272D, 0x1B282E, 0x1C292F, 0x1D292F, 0x1D2A30, 0x1E2B31, 0x1E2C32, 0x1F2C32, 0x1F2D33, 0x202E34};
    public static final int[] PURPLE = {0x160A21, 0x180B24, 0x1B0C27, 0x1D0D2A, 0x1F0E2D, 0x220F2F, 0x240F32, 0x261035, 0x291138, 0x2B123B, 0x2D133E, 0x2F1441, 0x321544, 0x341647, 0x37174A, 0x39174C, 0x3B184F, 0x3D1952, 0x3F1A54, 0x411B57, 0x431C59, 0x451C5C, 0x471D5E, 0x491E60, 0x4B1F63, 0x4E1F65, 0x502068, 0x52216A, 0x54226D, 0x56226F, 0x582371, 0x5A2474};
    public static final int[] ROSE = {0x1D1519, 0x1F161B, 0x22181D, 0x241A1F, 0x271B21, 0x291D23, 0x2B1E25, 0x2E2027, 0x302129, 0x32232A, 0x35242C, 0x37262E, 0x3A2830, 0x3C2932, 0x3E2B34, 0x412C36, 0x432E38, 0x452F3A, 0x47303C, 0x4A323D, 0x4C343F, 0x4E3541, 0x503643, 0x523845, 0x553947, 0x573A49, 0x593C4B, 0x5B3D4C, 0x5D3F4E, 0x604050, 0x624252, 0x644354};
    public static final int[] EMBER = {0x1E545E, 0x234C58, 0x274552, 0x2C3E4C, 0x303746, 0x352F3F, 0x3A2839, 0x3F2537, 0x452535, 0x4B2434, 0x502332, 0x562230, 0x5C212F, 0x68242C, 0x792828, 0x8A2C25, 0x9C3021, 0xAD341E, 0xBE381A, 0xCA3C17, 0xCF3E17, 0xD34116, 0xD84315, 0xDD4614, 0xE24813, 0xE34912, 0xD44410, 0xC63E0E, 0xB7390C, 0xA9340B, 0x9B2E09, 0x8C2908};

    /** The band routing, shared with sky.fsh / position.fsh / McsmStormPhase.java. */
    public static final float TEAL_TO_PURPLE_LO = 5.100F;
    public static final float TEAL_TO_PURPLE_HI = 5.500F;
    public static final float PURPLE_TO_ROSE_LO = 5.750F;
    public static final float PURPLE_TO_ROSE_HI = 6.050F;
    public static final float ROSE_TO_EMBER_LO = 7.000F;
    public static final float ROSE_TO_EMBER_HI = 8.050F;
// MCSM_BACKDROP_PALETTE_END

    private McsmBackdropPalette() {
    }

    /**
     * The backdrop colour of the band owning {@code phase}, at vertical {@code t}.
     *
     * <p>The three ramps are evaluated in the same nested order sky.fsh and the
     * pack's position program use, so the wall never jumps a band early or sits
     * a band behind: teal eases to purple across 5.10-5.50, purple to rose
     * across 5.75-6.05, and rose to the storyboard's ember tail across
     * 7.00-8.05.
     */
    public static int column(float phase, float t) {
        float a = ramp(phase, TEAL_TO_PURPLE_LO, TEAL_TO_PURPLE_HI);
        float b = ramp(phase, PURPLE_TO_ROSE_LO, PURPLE_TO_ROSE_HI);
        float c = ramp(phase, ROSE_TO_EMBER_LO, ROSE_TO_EMBER_HI);
        int out = 0;
        for (int k = 0; k < 3; k++) {
            float teal = channel(TEAL, t, k);
            float purple = channel(PURPLE, t, k);
            float rose = channel(ROSE, t, k);
            float ember = channel(EMBER, t, k);
            float v = teal + (purple - teal) * a;
            v = v + (rose - v) * b;
            v = v + (ember - v) * c;
            out |= clamp(Math.round(v)) << (16 - 8 * k);
        }
        return out;
    }

    /** One channel of a sheet column, linearly between the two stops around {@code t}. */
    private static float channel(int[] stops, float t, int k) {
        float u = Mth.clamp(t, 0.0F, 1.0F) * (STOPS - 1);
        int i = (int) u;
        float f = u - i;
        if (i > STOPS - 2) {
            i = STOPS - 2;
            f = 1.0F;
        }
        int low = (stops[i] >> (16 - 8 * k)) & 0xFF;
        int high = (stops[i + 1] >> (16 - 8 * k)) & 0xFF;
        return low + (high - low) * f;
    }

    /** Pack an {@code 0xRRGGBB} read of the sheets with an alpha byte. */
    public static int argb(int rgb, int alpha) {
        return (clamp(alpha) << 24) | (rgb & 0x00FFFFFF);
    }

    /** Smoothstep ramp, matching {@code mcsm_ramp} in the sky programs. */
    private static float ramp(float value, float low, float high) {
        if (high <= low) {
            return value >= high ? 1.0F : 0.0F;
        }
        float u = Mth.clamp((value - low) / (high - low), 0.0F, 1.0F);
        return u * u * (3.0F - 2.0F * u);
    }

    private static int clamp(int value) {
        return Math.max(0, Math.min(255, value));
    }
}
