package net.mcsm.extras.client;

import net.minecraft.util.Mth;

/**
 * BUILD #430 -- THE BACKDROP PALETTE. THE SUPPLIED SHEETS' COLOURS, IN ONE PLACE.
 *
 * <p>Both backdrop renderers used to carry their own hand-typed ramps: the
 * world-attached atmosphere wall ({@link McsmAtmosphericMeshComponent}) and the
 * story stage shell ({@link McsmExperimentalStoryStage}). Two hand-typed ramps
 * is one ramp too many. They disagreed with each other and with the three
 * supplied sheets, and nothing in the build could notice, because the sky
 * shader's columns are traced and parity-checked while the backdrops were not.
 * That is what "the colours haven't really changed at all" and "backdrops still
 * not the accurate colours" were looking at.
 *
 * <p>The stop block below is generated by {@code ci/sync_backdrop_palette.py}
 * out of {@code ci/palette_tables.py}, i.e. out of the SAME traced stop tables
 * the shipped sky wears, expanded from the supplied sheets. {@code --check}
 * fails the build if a single stop, a single routing boundary or the
 * interpolation itself ever stops matching them. Both renderers then read
 * {@link #column(float, float)} and keep no colour of their own.
 *
 * <p>{@code t} runs the way the sheets do: {@code t = 0} is the zenith (their
 * top row), {@code t = 1} is the horizon (their bottom row). The routing pairs
 * are sky.fsh's own, so the wall changes band at the same instant the sky does.
 */
public final class McsmBackdropPalette {

    /** Six stops per sheet: zenith, three quarters, middle, quarter, near horizon, horizon. */
    public static final int STOPS = 6;

    /** The near-black the atmosphere wall fades to along its lower edge. */
    public static final int VOID_BLACK = 0x010308;

    // MCSM_BACKDROP_PALETTE_BEGIN -- generated by ci/sync_backdrop_palette.py; do not hand-edit.
    // Source: ci/palette_tables.py, i.e. the stop tables the shipped sky wears,
    // expanded from the three supplied sheets. Stops run zenith -> horizon.
    public static final int[] TEAL = {0x0C1216, 0x10181D, 0x151F24, 0x19242A, 0x1C292F, 0x202E34};
    public static final int[] PURPLE = {0x160A21, 0x241033, 0x331545, 0x411B56, 0x4D1F65, 0x5A2474};
    public static final int[] ROSE = {0x1D1519, 0x2C1F25, 0x3B2831, 0x49313D, 0x563A48, 0x644354};
    public static final int[] EMBER = {0x1E545E, 0x3B2638, 0x5E212E, 0xC83B18, 0xE64A12, 0x8C2908};

    /** The band routing, shared with sky.fsh / position.fsh / McsmStormPhase.java. */
    public static final float TEAL_TO_PURPLE_LO = 5.100F;
    public static final float TEAL_TO_PURPLE_HI = 5.500F;
    public static final float PURPLE_TO_ROSE_LO = 5.750F;
    public static final float PURPLE_TO_ROSE_HI = 6.050F;
    public static final float ROSE_TO_EMBER_LO = 7.000F;
    public static final float ROSE_TO_EMBER_HI = 8.050F;
// MCSM_BACKDROP_PALETTE_END

    private McsmBackdropPalette() {
    }

    /**
     * The backdrop colour of the band owning {@code phase}, at vertical {@code t}.
     *
     * <p>The three ramps are evaluated in the same nested order sky.fsh and the
     * pack's position program use, so the wall never jumps a band early or sits
     * a band behind: teal eases to purple across 5.10-5.50, purple to rose
     * across 5.75-6.05, and rose to the storyboard's ember tail across
     * 7.00-8.05.
     */
    public static int column(float phase, float t) {
        float a = ramp(phase, TEAL_TO_PURPLE_LO, TEAL_TO_PURPLE_HI);
        float b = ramp(phase, PURPLE_TO_ROSE_LO, PURPLE_TO_ROSE_HI);
        float c = ramp(phase, ROSE_TO_EMBER_LO, ROSE_TO_EMBER_HI);
        int out = 0;
        for (int k = 0; k < 3; k++) {
            float teal = channel(TEAL, t, k);
            float purple = channel(PURPLE, t, k);
            float rose = channel(ROSE, t, k);
            float ember = channel(EMBER, t, k);
            float v = teal + (purple - teal) * a;
            v = v + (rose - v) * b;
            v = v + (ember - v) * c;
            out |= clamp(Math.round(v)) << (16 - 8 * k);
        }
        return out;
    }

    /** One channel of a sheet column, linearly between the two stops around {@code t}. */
    private static float channel(int[] stops, float t, int k) {
        float u = Mth.clamp(t, 0.0F, 1.0F) * (STOPS - 1);
        int i = (int) u;
        float f = u - i;
        if (i > STOPS - 2) {
            i = STOPS - 2;
            f = 1.0F;
        }
        int low = (stops[i] >> (16 - 8 * k)) & 0xFF;
        int high = (stops[i + 1] >> (16 - 8 * k)) & 0xFF;
        return low + (high - low) * f;
    }

    /** Pack an {@code 0xRRGGBB} read of the sheets with an alpha byte. */
    public static int argb(int rgb, int alpha) {
        return (clamp(alpha) << 24) | (rgb & 0x00FFFFFF);
    }

    /** Smoothstep ramp, matching {@code mcsm_ramp} in the sky programs. */
    private static float ramp(float value, float low, float high) {
        if (high <= low) {
            return value >= high ? 1.0F : 0.0F;
        }
        float u = Mth.clamp((value - low) / (high - low), 0.0F, 1.0F);
        return u * u * (3.0F - 2.0F * u);
    }

    private static int clamp(int value) {
        return Math.max(0, Math.min(255, value));
    }
}
