#!/usr/bin/env python3
"""1.9.220: port the REAL Vortex model (Telltale) into Java mesh arrays.

Reads Vortex.bbmodel (repo Loganwall111/gggggrff), extracts the 4 mesh
elements, normalizes their vertices to a unit cube, self-normalizes the
per-texture UVs, and emits McsmVortexMesh.java with static float arrays the
storm renderer submits as textured triangles -- replacing the procedural
swirls with the actual Telltale vortex geometry.
"""
import json, os, sys, base64

def main():
    root = '/home/user/gggggrff/ALL wither storm assets from MCSM for blockbench you\'ll ever need V0.9 4.zip'
    src = os.path.join(root, 'Misc/Vortex/Vortex.bbmodel')
    texdir = '/home/user/Lowuuuuuu/jar-overrides/assets/dabywitherstormmod/textures/mcsm_atmosphere'
    dst = '/home/user/Lowuuuuuu/mcsm-extras/java/net/mcsm/extras/client/McsmVortexMesh.java'
    d = json.load(open(src, encoding='utf-8', errors='replace'))
    texs = d.get('textures', [])
    els = [e for e in d['elements'] if e.get('vertices')]

    # 1) export the textures this model uses
    used = set()
    for e in els:
        for f in e['faces'].values():
            used.add(f.get('texture', 0))
    texname = {}
    for i in sorted(used):
        t = texs[i]
        name = t.get('name') or ('vortex_%d.png' % i)
        srcb64 = t.get('source', '')
        if srcb64.startswith('data:image/png;base64,'):
            raw = base64.b64decode(srcb64[len('data:image/png;base64,'):])
            outname = 'vortex_%s' % os.path.basename(name.replace('\\', '/'))
            out = os.path.join(texdir, outname)
            open(out, 'wb').write(raw)
            print('exported', outname, len(raw))
            texname[i] = outname
        else:
            texname[i] = 'vortex_%s' % os.path.basename(name.replace('\\', '/'))

    # 2) gather geometry per texture, normalize coords globally
    allpts = []
    for e in els:
        for v in e['vertices'].values():
            if isinstance(v, list) and len(v) >= 3:
                allpts.append(v[:3])
    mn = [min(p[i] for p in allpts) for i in range(3)]
    mx = [max(p[i] for p in allpts) for i in range(3)]
    span = max(mx[0]-mn[0], mx[1]-mn[1], mx[2]-mn[2]) or 1.0
    cx = (mn[0]+mx[0])/2.0; cy = (mn[1]+mx[1])/2.0; cz = (mn[2]+mx[2])/2.0
    print('vortex bounds span=%.1f centre=(%.1f,%.1f,%.1f)' % (span, cx, cy, cz))

    groups = {}
    for e in els:
        verts = e['vertices']
        for f in e['faces'].values():
            ids = f.get('vertices', [])
            if len(ids) < 3:
                continue
            ti = f.get('texture', 0)
            g = groups.setdefault(ti, {'pos': [], 'uv': [], 'idx': []})
            base = len(g['pos']) // 3
            uv = f.get('uv', {})
            for vid in ids:
                p = verts.get(vid)
                if p is None:
                    continue
                g['pos'] += [(p[0]-cx)/span, (p[1]-cy)/span, (p[2]-cz)/span]
                uvv = uv.get(vid, [0.0, 0.0])
                g['uv'] += [float(uvv[0]), float(uvv[1])]
                g['idx'].append(base)
                base += 1

    # 3) self-normalize uvs per group and emit the java class
    def chunks(vals, size=512, suffix='F'):
        return [','.join('%s%s' % (v, suffix) for v in vals[i:i+size]) for i in range(0, len(vals), size)]

    body = []
    body.append('package net.mcsm.extras.client;\n')
    body.append('/**\n * 1.9.220 -- the REAL Telltale vortex geometry, ported from\n * Vortex.bbmodel (repo Loganwall111/gggggrff). Generated by\n * ci/make_vortex_data.py; do not hand-edit.\n */\n')
    body.append('public final class McsmVortexMesh {\n')
    body.append('    private McsmVortexMesh() {}\n')
    body.append('    /** chunked so no single initializer exceeds the 64KB method cap. */\n')
    body.append('    private static float[] f(float[]... chunks) {\n')
    body.append('        int n = 0;\n')
    body.append('        for (float[] ch : chunks) {\n')
    body.append('            n += ch.length;\n')
    body.append('        }\n')
    body.append('        float[] out = new float[n];\n')
    body.append('        int o = 0;\n')
    body.append('        for (float[] ch : chunks) {\n')
    body.append('            System.arraycopy(ch, 0, out, o, ch.length);\n')
    body.append('            o += ch.length;\n')
    body.append('        }\n')
    body.append('        return out;\n')
    body.append('    }\n')
    body.append('    public static final class Group {\n')
    body.append('        public final String texture;\n')
    body.append('        public final float[] pos;\n')
    body.append('        public final float[] uv;\n')
    body.append('        public final int[] idx;\n')
    body.append('        public Group(String texture, float[] pos, float[] uv, int[] idx) {\n')
    body.append('            this.texture = texture; this.pos = pos; this.uv = uv; this.idx = idx;\n')
    body.append('        }\n    }\n')
    # normalize uvs first
    norm = {}
    for ti, g in groups.items():
        umin = min(g['uv'][0::2]); umax = max(g['uv'][0::2])
        vmin = min(g['uv'][1::2]); vmax = max(g['uv'][1::2])
        uspan = (umax - umin) or 1.0; vspan = (vmax - vmin) or 1.0
        uv = []
        for i in range(0, len(g['uv']), 2):
            uv += [(g['uv'][i] - umin) / uspan, (g['uv'][i+1] - vmin) / vspan]
        norm[ti] = uv

    body.append('    public static final Group[] GROUPS = new Group[] {\n')
    for n2, ti in enumerate(sorted(groups)):
        body.append('        g%d(),\n' % n2)
    body.append('    };\n')
    # each group's arrays live in their own methods (64KB per-method cap)
    for n2, ti in enumerate(sorted(groups)):
        g = groups[ti]
        uv = norm[ti]
        name = texname.get(ti, 'vortex_%d.png' % ti)
        pc = chunks(['%.5f' % v for v in g['pos']])
        uc = chunks(['%.5f' % v for v in uv])
        ic = chunks([str(v) for v in g['idx']], 512, '')
        body.append('    private static Group g%d() {\n' % n2)
        body.append('        return new Group("%s", pos%d(), uv%d(), idx%d());\n' % (name, n2, n2, n2))
        body.append('    }\n')
        body.append('    private static float[] pos%d() {\n' % n2)
        body.append('        return f(%s);\n' % ',\n                  '.join('new float[] {%s}' % c for c in pc))
        body.append('    }\n')
        body.append('    private static float[] uv%d() {\n' % n2)
        body.append('        return f(%s);\n' % ',\n                  '.join('new float[] {%s}' % c for c in uc))
        body.append('    }\n')
        body.append('    private static int[] idx%d() {\n' % n2)
        body.append('        return new int[] {%s};\n' % ',\n                  '.join(ic))
        body.append('    }\n')
        print('group tex=%s verts=%d tris=%d' % (name, len(g['pos'])//3, len(g['idx'])//3))
    body.append('}\n')
    open(dst, 'w').write('\n'.join(body))
    print('wrote', dst)

if __name__ == '__main__':
    main()
