#!/usr/bin/env python3
"""make_sky_sheets.py — Build #390 sky-gradient sheet generator.

The six Phase-3 gradient maps the build is specified around are *colour sheets*,
not photographs: each is a transparent vertical gradient (zenith at v=0, horizon
at v=1) that the sky pass folds between.  They are generated here from explicit
stop tables so the sheets can be regenerated byte-for-byte, reviewed in a diff,
and replaced by the user's own `image_*.png` files without touching any code:
the binding is by TARGET PATH only (see ci/SKY_SHEETS.md).

Storm backdrops (Phase 5+)
    textures/mcsm_atmosphere/sky/phase5_teal.png     Phase 5.0        TEAL
    textures/mcsm_atmosphere/sky/phase55.png         Phase 5.5-5.9    PURPLE (+ p55_purple alias)
    textures/mcsm_atmosphere/sky/phase6.png          Phase 6.0+       SALMON (+ p6_salmon alias)

Vanilla overworld cycle (no storm)
    textures/sky/day.png                             DAY (periwinkle-lilac)
    textures/sky/night.png                           MIDNIGHT BLUE
    textures/sky/sunset.png                          SUNSET SPLIT (teal-orange-maroon)
    (+ vanilla_day_blue / vanilla_night_lavender / vanilla_sunset_split aliases)

Everything else in those folders is left byte-identical.  The previous gradient
sheets are copied to ci/legacy_sky_sheets/<relative path> first (outside the
shipped trees, so the jar stays clean), so the look is revertible.

Usage:
    python3 ci/make_sky_sheets.py            # write sheets (+ legacy backups)
    python3 ci/make_sky_sheets.py --dry-run  # print the plan, write nothing
"""
import argparse
import os
import shutil
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "glslcheck"))

SIZE = 1024
# (name, stops) — stops are (t, (r, g, b), alpha) with t=0 at the zenith.
# Values are the sampled reference palettes the build note specifies, in the
# same 0..1 artist space the rest of the MCSM shader constants use.
SHEETS = {
    # BUILD #390 re-trace: stops sampled off the attached artist sheets
    # (phase 5 turquoise sky.png / phase5sky0purple sky.png /
    # phase6sky 6 witherstorm.png / skyday day.png / sky 2 midnight.png /
    # storymode_sky_sunset.png). Horizons are DESATURATED on purpose -- the
    # attached storm sheets fade to sage/orchid/dusty-rose, not neon.
    "phase5_teal": [
        (0.00, (0.078, 0.149, 0.157), 0),
        (0.14, (0.140, 0.220, 0.215), 170),
        (0.42, (0.290, 0.360, 0.350), 235),
        (0.72, (0.470, 0.530, 0.505), 250),
        (0.94, (0.600, 0.660, 0.615), 255),
        (1.00, (0.620, 0.675, 0.625), 255),
    ],
    "phase55": [
        (0.00, (0.165, 0.059, 0.196), 0),
        (0.16, (0.240, 0.100, 0.270), 176),
        (0.44, (0.361, 0.165, 0.400), 238),
        (0.74, (0.525, 0.275, 0.557), 250),
        (0.93, (0.640, 0.345, 0.690), 255),
        (1.00, (0.660, 0.361, 0.706), 255),
    ],
    "phase6": [
        (0.00, (0.329, 0.282, 0.329), 0),
        (0.15, (0.400, 0.340, 0.380), 172),
        (0.43, (0.478, 0.392, 0.439), 236),
        (0.72, (0.612, 0.510, 0.533), 250),
        (0.92, (0.760, 0.600, 0.640), 255),
        (1.00, (0.784, 0.612, 0.651), 255),
    ],
    "day": [
        (0.00, (0.482, 0.482, 0.878), 0),
        (0.12, (0.520, 0.510, 0.900), 180),
        (0.46, (0.610, 0.560, 0.930), 240),
        (0.78, (0.760, 0.660, 0.950), 252),
        (0.96, (0.851, 0.714, 0.961), 255),
        (1.00, (0.867, 0.737, 0.969), 255),
    ],
    "night": [
        (0.00, (0.051, 0.051, 0.157), 0),
        (0.12, (0.090, 0.100, 0.260), 178),
        (0.44, (0.137, 0.161, 0.408), 238),
        (0.74, (0.200, 0.235, 0.620), 250),
        (0.94, (0.290, 0.353, 0.831), 255),
        (1.00, (0.230, 0.260, 0.640), 255),
    ],
    "sunset": [
        (0.00, (0.118, 0.329, 0.369), 0),
        (0.13, (0.230, 0.360, 0.380), 176),
        (0.36, (0.369, 0.416, 0.400), 236),
        (0.48, (0.784, 0.345, 0.094), 244),
        (0.58, (0.973, 0.376, 0.031), 250),
        (0.78, (0.690, 0.227, 0.204), 255),
        (1.00, (0.431, 0.157, 0.212), 255),
    ],
}

# target path -> (sheet name, [alias file names])
STORM_DIR = "assets/dabywitherstormmod/textures/mcsm_atmosphere/sky"
VANILLA_DIR = "assets/dabywitherstormmod/textures/sky"
TARGETS = [
    (STORM_DIR + "/phase5_teal.png", "phase5_teal", []),
    (STORM_DIR + "/phase55.png", "phase55", ["p55_purple.png"]),
    (STORM_DIR + "/phase6.png", "phase6", ["p6_salmon.png"]),
    (VANILLA_DIR + "/day.png", "day", ["vanilla_day_blue.png"]),
    (VANILLA_DIR + "/night.png", "night", ["vanilla_night_lavender.png"]),
    (VANILLA_DIR + "/sunset.png", "sunset", ["vanilla_sunset_split.png"]),
]
ROOTS = ["src/main/resources", "jar-overrides"]


def lerp(a, b, t):
    return a + (b - a) * t


def sample(stops, t):
    """Piecewise-linear sample of the stop table -> (r, g, b, a) in 0..255."""
    if t <= stops[0][0]:
        c, a = stops[0][1], stops[0][2]
        return (int(c[0] * 255), int(c[1] * 255), int(c[2] * 255), a)
    for (t0, c0, a0), (t1, c1, a1) in zip(stops, stops[1:]):
        if t <= t1:
            u = 0.0 if t1 <= t0 else (t - t0) / (t1 - t0)
            return (
                int(round(lerp(c0[0], c1[0], u) * 255)),
                int(round(lerp(c0[1], c1[1], u) * 255)),
                int(round(lerp(c0[2], c1[2], u) * 255)),
                int(round(lerp(a0, a1, u))),
            )
    c, a = stops[-1][1], stops[-1][2]
    return (int(c[0] * 255), int(c[1] * 255), int(c[2] * 255), a)


def rows(stops, size=SIZE):
    """Yield per-row (r,g,b,a). Rows are constant horizontally: these are
    gradient *sheets*, so a row-major row is one colour."""
    for y in range(size):
        yield sample(stops, y / (size - 1))


def write_sheet(path, stops, size=SIZE):
    """Write an RGBA8 PNG. Filter 0 rows (the repo's pngtools convention), so
    the file stays readable by every tool in ci/ without a Pillow dependency."""
    raw = bytearray()
    stride = size * 4
    row_bytes = []
    for r, g, b, a in rows(stops, size):
        row_bytes.append(bytes((r, g, b, a)) * size)
    for rb in row_bytes:
        raw.append(0)
        raw += rb

    def chunk(typ, data):
        c = struct.pack(">I", len(data)) + typ + data
        return c + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBB", size, size, 8, 6) + b"\x00\x00\x00"
    blob = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(bytes(raw), 9)) + chunk(b"IEND", b""))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(blob)
    return len(blob)


LEGACY_ROOT = "ci/legacy_sky_sheets"


def backup_legacy(path):
    """One-time copy of the pre-390 sheet into ci/legacy_sky_sheets/ so the previous
    gradient look can be restored by a single `cp`."""
    if not os.path.isfile(path):
        return None
    rel = os.path.relpath(path, ROOT)
    legacy_dir = os.path.join(ROOT, LEGACY_ROOT, os.path.dirname(rel))
    os.makedirs(legacy_dir, exist_ok=True)
    dest = os.path.join(legacy_dir, os.path.basename(path))
    if not os.path.isfile(dest):
        shutil.copy2(path, dest)
        return dest
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    total = 0
    for rel, sheet, aliases in TARGETS:
        stops = SHEETS[sheet]
        for root in ROOTS:
            path = os.path.join(ROOT, root, rel)
            if args.dry_run:
                print("[plan] write %s  (%d stops, %dx%d)" % (path, len(stops), SIZE, SIZE))
                for alias in aliases:
                    print("[plan] alias %s" % os.path.join(os.path.dirname(path), alias))
                continue
            backed = backup_legacy(path)
            if backed:
                print("[legacy] %s" % os.path.relpath(backed, ROOT))
            size = write_sheet(path, stops)
            total += size
            print("[sheet] %-64s %7d B" % (os.path.relpath(path, ROOT), size))
            for alias in aliases:
                alias_path = os.path.join(os.path.dirname(path), alias)
                size = write_sheet(alias_path, stops)
                total += size
                print("[ alias] %-64s %7d B" % (os.path.relpath(alias_path, ROOT), size))
    if not args.dry_run:
        print("[done] %d sheet files, %.1f KiB total" % (
            sum(1 + len(a) for _, _, a in TARGETS) * len(ROOTS), total / 1024.0))


if __name__ == "__main__":
    main()
