#!/usr/bin/env python3
"""make_backdrop_sheets.py -- Build #415 backdrop canvas + cloud-filter sheets.

WHY THIS EXISTS
---------------
The 2D background skybox sticker queue (src-recon .../client/StormBackdrop.java)
used to paint nothing but three smoke sheets, so the flat purple sky canvas and
the transparent teal / salmon-pink cloud filters the storyboard calls for were
missing: the frame was handed back to the vanilla sky in every phase where the
sheets had faded out.

This script bakes the three missing primitives as colour sheets -- not
photographs -- from explicit stop tables, exactly like ci/make_sky_sheets.py on
the ds-1.9.390 line, so they can be regenerated byte-for-byte, reviewed in a
diff, and replaced by the user's own art without touching any code (the binding
is by TARGET PATH only).

PROVENANCE OF THE STOP TABLES
-----------------------------
* purple canvas ....... ds-1.9.390 `ci/make_sky_sheets.py` "phase55" sheet
                        (#2A123D zenith -> #7F3AA6 horizon), deepened at the
                        zenith so it reads as a canvas rather than a haze, and
                        blended toward the Story Mode plum (#A0757E) low band.
* teal cloud filter ... ds-1.9.390 "phase5_teal" sheet (#1D3335 -> #557061),
                        rebuilt with a cloud-streak alpha instead of a solid
                        vertical ramp, which is what makes it a FILTER: the
                        purple canvas shows through the gaps.
* salmon filter ....... ds-1.9.390 "phase6" sheet (#8A5361 -> #C47A5A), same
                        cloud-streak treatment (the salmon-pink phase-6 deck).

WHERE THEY LAND (both roots, so the jar override and the dev tree agree)
    src/main/resources/assets/dabywitherstormmod/textures/misc/
    jar-overrides/assets/dabywitherstormmod/textures/misc/
        backdrop_sheet_purple_canvas.png    base sky canvas      (opaque)
        backdrop_sheet_teal_filter.png      phase 5 cloud filter (transparent)
        backdrop_sheet_salmon_filter.png    phase 6 cloud filter (transparent)

The pre-existing smoke sheets (backdrop_sheet_phase5_teal / phase55_violet /
phase6_plum) are NOT touched: the canvas + filters are additional layers in the
sticker stack, so the current look stays intact underneath them.

Usage:
    python3 ci/make_backdrop_sheets.py            # write the sheets
    python3 ci/make_backdrop_sheets.py --dry-run  # print the plan, write nothing
"""
import argparse
import math
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Matches the shipped smoke sheets exactly (256x128 RGBA8, filter-0 rows).
WIDTH = 256
HEIGHT = 128

MISC_DIR = "assets/dabywitherstormmod/textures/misc"
ROOTS = ["src/main/resources", "jar-overrides"]

# (path, stops, cloud_streaks)
#   stops: (t, (r, g, b), alpha) with t = 0 at the zenith, 1 at the horizon.
#   cloud_streaks: 0.0 = solid vertical gradient (canvas); >0 = the alpha is
#                  modulated by a horizontal cloud field (filter).
SHEETS = [
    (
        MISC_DIR + "/backdrop_sheet_purple_canvas.png",
        [
            (0.00, (0.055, 0.028, 0.105), 214),
            (0.18, (0.120, 0.055, 0.180), 232),
            (0.46, (0.235, 0.105, 0.310), 246),
            (0.74, (0.400, 0.180, 0.420), 252),
            (0.93, (0.525, 0.270, 0.420), 255),
            (1.00, (0.560, 0.320, 0.420), 255),
        ],
        0.0,
    ),
    (
        MISC_DIR + "/backdrop_sheet_teal_filter.png",
        [
            (0.00, (0.114, 0.200, 0.208), 0),
            (0.16, (0.170, 0.255, 0.250), 150),
            (0.44, (0.290, 0.360, 0.350), 215),
            (0.72, (0.470, 0.530, 0.505), 235),
            (0.94, (0.600, 0.660, 0.615), 246),
            (1.00, (0.620, 0.675, 0.625), 248),
        ],
        0.62,
    ),
    (
        MISC_DIR + "/backdrop_sheet_salmon_filter.png",
        [
            (0.00, (0.329, 0.282, 0.329), 0),
            (0.15, (0.400, 0.340, 0.380), 140),
            (0.43, (0.478, 0.392, 0.439), 205),
            (0.72, (0.612, 0.510, 0.533), 232),
            (0.92, (0.760, 0.600, 0.560), 244),
            (1.00, (0.784, 0.612, 0.545), 246),
        ],
        0.70,
    ),
]


def lerp(a, b, t):
    return a + (b - a) * t


def sample(stops, t):
    """Piecewise-linear sample of a stop table -> (r, g, b, a) in 0..255."""
    if t <= stops[0][0]:
        c, a = stops[0][1], stops[0][2]
        return (c[0] * 255.0, c[1] * 255.0, c[2] * 255.0, float(a))
    for (t0, c0, a0), (t1, c1, a1) in zip(stops, stops[1:]):
        if t <= t1:
            u = 0.0 if t1 <= t0 else (t - t0) / (t1 - t0)
            return (
                lerp(c0[0], c1[0], u) * 255.0,
                lerp(c0[1], c1[1], u) * 255.0,
                lerp(c0[2], c1[2], u) * 255.0,
                lerp(float(a0), float(a1), u),
            )
    c, a = stops[-1][1], stops[-1][2]
    return (c[0] * 255.0, c[1] * 255.0, c[2] * 255.0, float(a))


def _hash2(x, y):
    """Deterministic 0..1 hash -- no RNG state, so the sheets are reproducible
    on every machine and every rerun (the whole point of a baked sheet)."""
    n = math.sin(x * 127.1 + y * 311.7) * 43758.5453
    return n - math.floor(n)


def _noise2(x, y):
    """Bilinear value noise."""
    xi, yi = math.floor(x), math.floor(y)
    xf, yf = x - xi, y - yi
    u = xf * xf * (3.0 - 2.0 * xf)
    v = yf * yf * (3.0 - 2.0 * yf)
    a = _hash2(xi, yi)
    b = _hash2(xi + 1, yi)
    c = _hash2(xi, yi + 1)
    d = _hash2(xi + 1, yi + 1)
    return lerp(lerp(a, b, u), lerp(c, d, u), v)


def _fbm(x, y, octaves=4):
    total = 0.0
    amp = 0.5
    freq = 1.0
    for _ in range(octaves):
        total += amp * _noise2(x * freq, y * freq)
        freq *= 2.03
        amp *= 0.5
    return total


def cloud_alpha(x, y, strength):
    """Horizontal cloud banding: stretched noise so the filter reads as cloud
    decks drifting across the canvas instead of a flat wash."""
    if strength <= 0.0:
        return 1.0
    # horizontal stretch (4x) -- the same ratio the in-game smog layer uses
    n1 = _fbm(x / WIDTH * 3.2, y / HEIGHT * 1.6)
    n2 = _fbm(x / WIDTH * 7.5 + 11.0, y / HEIGHT * 3.1 + 5.0)
    streak = 0.62 * n1 + 0.38 * n2
    # a soft floor keeps some cover everywhere; the streaks do the shaping
    cover = 0.42 + 0.58 * streak
    return lerp(1.0, cover, strength)


def write_sheet(path, stops, streak_strength):
    """Write an RGBA8 PNG (filter 0 rows -- the repo's pngtools convention, so
    the file stays readable by every tool in ci/ without a Pillow dependency)."""
    raw = bytearray()
    for y in range(HEIGHT):
        raw.append(0)  # filter type 0 for this row
        t = y / (HEIGHT - 1)
        r, g, b, a = sample(stops, t)
        rgb = (
            max(0, min(255, int(round(r)))),
            max(0, min(255, int(round(g)))),
            max(0, min(255, int(round(b)))),
        )
        for x in range(WIDTH):
            if streak_strength <= 0.0:
                aa = int(round(a))
            else:
                # per-column variation so the streaks are not perfectly vertical
                aa = int(round(a * cloud_alpha(x + 0.5, y + 0.5, streak_strength)))
            raw += struct.pack("BBBB", rgb[0], rgb[1], rgb[2], max(0, min(255, aa)))

    def chunk(typ, data):
        c = struct.pack(">I", len(data)) + typ + data
        return c + struct.pack(">I", zlib.crc32(typ + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBB", WIDTH, HEIGHT, 8, 6) + b"\x00\x00\x00"
    blob = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", ihdr)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(blob)
    return len(blob)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    total = 0
    written = 0
    for rel, stops, streaks in SHEETS:
        for root in ROOTS:
            path = os.path.join(ROOT, root, rel)
            if args.dry_run:
                print("[plan] write %s (%dx%d, %d stops, streaks %.2f)"
                      % (path, WIDTH, HEIGHT, len(stops), streaks))
                continue
            size = write_sheet(path, stops, streaks)
            total += size
            written += 1
            print("[sheet] %-72s %7d B" % (os.path.relpath(path, ROOT), size))
    if args.dry_run:
        print("[plan] %d files" % (len(SHEETS) * len(ROOTS)))
        return 0
    print("[done] %d sheet files, %.1f KiB total" % (written, total / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
