#!/usr/bin/env python3
"""measure_stills.py -- BUILD #435: the supplied ground-truth frames, in numbers.

WHY
---
The artist uploaded the real thing -- six clean flat frames of the storm's own
atmosphere, harvested from the show (the repo root, "Screenshot 2026-09-12
0833xx.png" / "0835xx.png"). Every one of them says the same thing about the
atmospheric backdrop, and it is not what the code was drawing:

  * NO EDGE ANYWHERE. There is no dome, no shell, no card and no rim: the field
    dissolves at its top and at its bottom and is at most a soft penumbra around
    the body, the way a shadow is. The build's field had a constant-radius core
    with a tenth-of-the-radius blend, i.e. a hard black DISC behind the creature
    -- this is the file that made that measurable.
  * The body's own mass is near-black (#000000 to #000C18), 23% of a frame at the
    close-ups, with the aura living in the MID-TONES around it (#231C35),
    never as a saturated band.
  * The brightest thing in the sky is the horizon -- #E5B1AA pink at the bottom
    of the low frame -- and the sky above it runs #3C2E4B slate violet through
    #725177 amethyst.
  * The beams are the only saturated colour: magenta at the root, washing to
    white where they land, with the white dotted ellipse rings and one magenta
    dot on each -- the tracking eyes and the teeth.
  * The clouds stay VANILLA white and full-bright under all of it.

WHAT THIS DOES
--------------
Measures each supplied frame into numbers -- size, a vertical band table, the
dominant opaque colours with their share -- and writes them into
`ci/ATMOSPHERE_REFERENCE.md`. `--check` re-measures and fails if the table has
drifted from the frames, so replacing a still or a band count is a build event
rather than a silent inconsistency. The numbers are the ones the backdrop work is
judged against; nothing here reads the game, so it runs in CI with no JDK.

Usage:
    python3 ci/measure_stills.py            # write ci/ATMOSPHERE_REFERENCE.md
    python3 ci/measure_stills.py --check    # 0 = the table matches the frames
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import pngutil  # noqa: E402

BANDS = 5
OUT = os.path.join(ROOT, "ci", "ATMOSPHERE_REFERENCE.md")

# The supplied frames, in the order they were uploaded. Each one is tagged with
# what it is evidence FOR, so a reader does not have to guess why it is kept.
FRAMES = [
    ("Screenshot 2026-09-12 083320.png", "the low sky: violet zenith -> amethyst -> pink horizon"),
    ("Screenshot 2026-09-12 083352.png", "the field at close range: near-black mass, soft aura, no rim"),
    ("Screenshot 2026-09-12 083410.png", "the teal end of the sky, same construction"),
    ("Screenshot 2026-09-12 083432.png", "the mouth: white dotted ellipse rings, one magenta dot each"),
    ("Screenshot 2026-09-12 083458.png", "the beams and the dark body mass over a pink horizon"),
    ("Screenshot 2026-09-12 083545.png", "the field's own edge: it dissolves, it does not stop"),
]


def band_table(w, h, px, bands=BANDS):
    out = []
    for b in range(bands):
        y0 = h * b // bands
        y1 = max(y0 + 1, h * (b + 1) // bands)
        rs = gs = bs = n = 0
        for y in range(y0, y1):
            base = y * w
            for x in range(w):
                r, g, bl, _a = px[base + x]
                rs += r
                gs += g
                bs += bl
                n += 1
        out.append((rs // n, gs // n, bs // n))
    return out


def measure(rel):
    w, h, px = pngutil.read_png(os.path.join(ROOT, rel))
    return {
        "size": (w, h),
        "bands": band_table(w, h, px),
        "dominant": pngutil.dominant(px, w, h, bins=6)[:6],
    }


def report():
    lines = [
        "# The atmosphere's ground truth, measured",
        "",
        "Generated by `ci/measure_stills.py` from the frames the artist supplied.",
        "**Do not hand-edit**: `python3 ci/measure_stills.py` rewrites it and",
        "`--check` fails the build if it has drifted from the frames.",
        "",
        "Every band is the mean colour of a horizontal fifth of the frame, top to",
        "bottom. The dominant list is the top opaque colours by share of the frame.",
        "",
        "What all six agree on, and what the backdrop code is judged against:",
        "",
        "* no edge, no rim, no dome and no card -- the field dissolves at its top",
        "  and bottom, and is a soft penumbra around the body rather than a disc;",
        "* the body's mass is near-black, and the aura lives in the mid-tones;",
        "* the horizon is the brightest row in the sky and the beams are the only",
        "  saturated colour;",
        "* the clouds stay vanilla white and full-bright underneath all of it.",
        "",
    ]
    for rel, note in FRAMES:
        m = measure(rel)
        w, h = m["size"]
        lines.append("## `%s` -- %dx%d" % (rel, w, h))
        lines.append("")
        lines.append("_%s_" % note)
        lines.append("")
        lines.append("| band (top to bottom) | mean colour | rgb |")
        lines.append("| --- | --- | --- |")
        for i, (r, g, b) in enumerate(m["bands"]):
            lines.append("| %d/%d | `#%02X%02X%02X` | (%d, %d, %d) |"
                         % (i + 1, len(m["bands"]), r, g, b, r, g, b))
        lines.append("")
        lines.append("dominant: " + ", ".join(
            "`#%02X%02X%02X` %.2f%%" % (rgb[0], rgb[1], rgb[2], share)
            for rgb, share in m["dominant"]))
        lines.append("")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    missing = [rel for rel, _ in FRAMES if not os.path.isfile(os.path.join(ROOT, rel))]
    if missing:
        print("[stills] FAIL -- the supplied frames are not in the tree: %s"
              % ", ".join(missing))
        return 1

    want = report()
    if args.check:
        if not os.path.isfile(OUT):
            print("[stills] FAIL -- ci/ATMOSPHERE_REFERENCE.md is missing "
                  "(run: python3 ci/measure_stills.py)")
            return 1
        with open(OUT, encoding="utf-8") as f:
            have = f.read()
        if have != want:
            print("[stills] FAIL -- the measured table and the supplied frames disagree "
                  "(run: python3 ci/measure_stills.py)")
            return 1
        print("[stills] OK -- %d supplied frames, %d bands each, table in sync"
              % (len(FRAMES), BANDS))
        return 0

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(want)
    print("[stills] wrote %s (%d frames)" % (os.path.relpath(OUT, ROOT), len(FRAMES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
