#!/usr/bin/env python3
"""sync_backdrop_palette.py -- BUILD #430: ONE backdrop palette, and it is the sheets'.

WHY THIS EXISTS
---------------
The sky shader's columns are traced off the three supplied sheets and parity
checked (ci/palette_tables.py): the GLSL, the pack's position program and the
Java halo feed must all carry the same numbers. The two BACKDROP renderers were
never in that chain, and each carried its own hand-typed horizon/zenith ramp:

    McsmAtmosphericMeshComponent   #6E7873 -> #1D2B2B, #7F3AA6 -> #1A0A2A, ...
    McsmExperimentalStoryStage     #557061 -> #101617, #4B1E5E -> #050208, ...

Two hand-typed ramps is one ramp too many. They disagreed with each other and
with the sheets, and nothing in the build could notice -- which is what "the
colours haven't really changed at all" and "backdrops still not the accurate
colours" were looking at.

WHAT IT WRITES
--------------
The generated block inside `McsmBackdropPalette.java`:

  * the four traced columns (six stops each, 0xRRGGBB, zenith -> horizon), read
    straight out of `palette_tables.load()` -- i.e. out of the shipped sky;
  * the three routing pairs sky.fsh / position.fsh / McsmStormPhase.java use
    (5.10-5.50, 5.75-6.05, 7.00-8.05), so the wall changes band exactly when the
    sky does.

Both backdrop renderers then own no colour of their own.

CHECKS (`--check`, the build gate)
----------------------------------
  1. every generated stop equals its traced column, to 1/255;
  2. every routing pair equals palette_tables' own;
  3. a numeric sweep: this module re-implements the Java `column()` out of the
     PARSED JAVA DATA and compares it against `palette_tables.column()` across
     phase 4.40 -> 8.10 and vertical 0.0 -> 1.0. Data parity alone would not
     catch a wrong interpolation; this does.

Usage:
    python3 ci/sync_backdrop_palette.py            # write the block
    python3 ci/sync_backdrop_palette.py --check    # 0 = in sync, 1 = drifted
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import palette_tables as pal  # noqa: E402

TARGET = os.path.join(ROOT, "mcsm-extras", "java", "net", "mcsm", "extras", "client",
                      "McsmBackdropPalette.java")
BEGIN = "// MCSM_BACKDROP_PALETTE_BEGIN"
END = "// MCSM_BACKDROP_PALETTE_END"

ROLE_CONST = {
    "teal": "TEAL",
    "purple": "PURPLE",
    "rose": "ROSE",
    "ember": "EMBER",
}
ROUTES = [
    ("TEAL_TO_PURPLE", pal.TEAL_TO_PURPLE),
    ("PURPLE_TO_ROSE", pal.PURPLE_TO_ROSE),
    ("ROSE_TO_EMBER", pal.ROSE_TO_EMBER),
]


def traced():
    """{ROLE_CONST: [0xRRGGBB x 6]} -- the sheets, via the shipped sky."""
    out = {}
    for role, name in ROLE_CONST.items():
        rows = pal.rows(role)
        if len(rows) == 1:
            rows = rows * pal.STOPS
        if len(rows) != pal.STOPS:
            raise SystemExit("%s: %d stops, expected %d" % (role, len(rows), pal.STOPS))
        out[name] = [pal.argb(row) & 0xFFFFFF for row in rows]
    return out


def block():
    """The generated text, from BEGIN through END inclusive."""
    stops = traced()
    lines = [BEGIN + " -- generated by ci/sync_backdrop_palette.py; do not hand-edit.",
             "    // Source: ci/palette_tables.py, i.e. the stop tables the shipped sky wears,",
             "    // expanded from the three supplied sheets. Stops run zenith -> horizon."]
    for name in ("TEAL", "PURPLE", "ROSE", "EMBER"):
        rows = stops[name]
        body = ", ".join("0x%06X" % v for v in rows)
        lines.append("    public static final int[] %s = {%s};" % (name, body))
    lines.append("")
    lines.append("    /** The band routing, shared with sky.fsh / position.fsh / McsmStormPhase.java. */")
    for name, (lo, hi) in ROUTES:
        lines.append("    public static final float %s_LO = %.3fF;" % (name, lo))
        lines.append("    public static final float %s_HI = %.3fF;" % (name, hi))
    lines.append(END)
    return "\n".join(lines)


def current():
    text = open(TARGET, encoding="utf-8").read()
    i = text.find(BEGIN)
    j = text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("%s: no %s .. %s block" % (TARGET, BEGIN, END))
    return text, text[i:j + len(END)]


# ---------------------------------------------------------------------------
# The check: parsed Java data, mirrored Java maths, compared to the traced
# blueprints.
# ---------------------------------------------------------------------------
def parse_java(text):
    data = {}
    for m in re.finditer(r"int\[\]\s+([A-Z0-9_]+)\s*=\s*\{([^}]*)\}", text):
        vals = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{6})", m.group(2))]
        if vals:
            data[m.group(1)] = vals
    routes = {}
    for m in re.finditer(r"float\s+([A-Z0-9_]+)_(LO|HI)\s*=\s*([0-9.]+)F\s*;", text):
        routes.setdefault(m.group(1), {})[m.group(2)] = float(m.group(3))
    return data, routes


def _ramp(v, lo, hi):
    if hi <= lo:
        return 1.0 if v >= hi else 0.0
    t = max(0.0, min(1.0, (v - lo) / (hi - lo)))
    return t * t * (3.0 - 2.0 * t)


def _deck(stops, t):
    """`McsmBackdropPalette.deck`: six stops, linear between neighbours."""
    u = max(0.0, min(1.0, t)) * (len(stops) - 1.0)
    i = int(u)
    f = u - i
    if i > len(stops) - 2:
        i, f = len(stops) - 2, 1.0
    a, b = stops[i], stops[i + 1]
    out = []
    for k in range(3):
        av = (a >> (16 - 8 * k)) & 0xFF
        bv = (b >> (16 - 8 * k)) & 0xFF
        out.append(av + (bv - av) * f)
    return out


def java_column(phase, t, data, routes):
    """`McsmBackdropPalette.column`, done in Python on the parsed Java data."""
    teal = _deck(data["TEAL"], t)
    purple = _deck(data["PURPLE"], t)
    rose = _deck(data["ROSE"], t)
    ember = _deck(data["EMBER"], t)
    a = _ramp(phase, routes["TEAL_TO_PURPLE"]["LO"], routes["TEAL_TO_PURPLE"]["HI"])
    b = _ramp(phase, routes["PURPLE_TO_ROSE"]["LO"], routes["PURPLE_TO_ROSE"]["HI"])
    c = _ramp(phase, routes["ROSE_TO_EMBER"]["LO"], routes["ROSE_TO_EMBER"]["HI"])
    out = [teal[k] + (purple[k] - teal[k]) * a for k in range(3)]
    out = [out[k] + (rose[k] - out[k]) * b for k in range(3)]
    out = [out[k] + (ember[k] - out[k]) * c for k in range(3)]
    return out


def check(verbose=False, sweep_step=0.05):
    fails = []
    text, _ = current()
    data, routes = parse_java(text)

    want = traced()
    for name, vals in want.items():
        got = data.get(name)
        if got != vals:
            fails.append("data drift: %s = %s, sheets say %s"
                         % (name,
                            " ".join("0x%06X" % v for v in (got or [])),
                            " ".join("0x%06X" % v for v in vals)))
        elif verbose:
            print("  data ok: %s = %s" % (name, " ".join("0x%06X" % v for v in vals)))

    for name, (lo, hi) in ROUTES:
        got = routes.get(name)
        if not got or abs(got["LO"] - lo) > 1e-6 or abs(got["HI"] - hi) > 1e-6:
            fails.append("routing drift: %s = %s, the sky uses %.2f-%.2f"
                         % (name, got, lo, hi))
        elif verbose:
            print("  routing ok: %s = %.2f-%.2f" % (name, lo, hi))

    if not fails:
        worst = 0.0
        where = ""
        phase = 4.40
        while phase <= 8.1001:
            for ti in range(11):
                t = ti / 10.0
                mine = java_column(phase, t, data, routes)
                ref = pal.column(phase, t)
                for k in range(3):
                    mine8 = max(0, min(255, int(round(mine[k]))))
                    ref8 = max(0, min(255, int(round(ref[k] * 255.0))))
                    d = abs(mine8 - ref8)
                    if d > worst:
                        worst = d
                        where = "phase %.2f t %.1f channel %d: %d vs %d" % (
                            phase, t, k, mine8, ref8)
            phase += sweep_step
        if worst > 1:
            fails.append("interpolation drift: worst channel distance %d (%s)" % (worst, where))
        elif verbose:
            print("  sweep ok: phases 4.40-8.10, t 0.0-1.0, worst channel distance %d" % worst)

    return fails, worst


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    text, found = current()
    want = block()

    if args.check:
        fails, worst = check(verbose=args.verbose)
        if found != want:
            fails.append("the generated block is not what this script writes "
                         "(run: python3 ci/sync_backdrop_palette.py)")
        if fails:
            print("[backdrop] FAIL")
            for f in fails:
                print("  - %s" % f)
            return 1
        print("[backdrop] OK -- both backdrops wear the supplied sheets' traced columns "
              "(4 columns x 6 stops, routing 3 pairs, sweep worst channel %d)" % worst)
        return 0

    if found == want:
        print("[backdrop] already in sync -- nothing written")
        return 0
    open(TARGET, "w", encoding="utf-8").write(text.replace(found, want, 1))
    print("[backdrop] wrote the traced palette into %s"
          % os.path.relpath(TARGET, ROOT).replace(os.sep, "/"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
