import fs from 'fs';
let pass=0,fail=0;const ok=(n,c)=>{if(c)pass++;else{fail++;console.log('FAIL: '+n);}};
const world=fs.readFileSync('src/bjs/worlds/BlackHoleWorld.ts','utf8');
const renderer=fs.readFileSync('src/bjs/systems/HoleFieldRenderer.ts','utf8');
const frag=(world.match(/const\s+FRAG\s*=\s*`([\s\S]*?)`;/m)||[])[1]||'';
ok('canonical material fragment exists',frag.length>5000);
ok('canonical material is exported',world.includes('WORKING_SINGULARITY_FRAG'));
ok('open-world holes import the canonical fragment',renderer.includes('WORKING_SINGULARITY_FRAG'));
ok('open-world holes import the canonical vertex stage',renderer.includes('WORKING_SINGULARITY_VERT'));
ok('there is no alternate open-world shader',!renderer.includes('HoleFieldShader'));
ok('the material reconstructs a ray per pixel',/vec3 rayL = safeNormalize/.test(frag));
ok('the material performs a bounded geodesic march',/for \(int i = 0; i < STEPS; i\+\+\)/.test(frag));
ok('the Schwarzschild ODE is integrated',/1\.5 \* rs \* u \* u/.test(frag));
ok('RK2 midpoint integration is used',/uMid/.test(frag)&&/k2/.test(frag));
ok('captured photons are explicitly tracked',/bool captured = false/.test(frag));
ok('the horizon capture radius uses rs',/r <= rs/.test(frag));
ok('disk gas is sampled during the ray march',/inSlab/.test(frag));
ok('the disk has volumetric thickness',/abs\(d1\) <= diskThickness/.test(frag));
ok('starved holes can skip disk emission',/diskThickness > 0\.0/.test(frag));
ok('the shader has a directional star field',/vec3 stars\(vec3 dir\)/.test(frag));
ok('the shader carries an interior amount',/uniform float insideAmt/.test(frag));
ok('the exit is directional',/uniform vec3\s+exitDir/.test(frag));
ok('nested singularity travel is supported',/uniform float nestedLens/.test(frag));
ok('the output is opaque',/gl_FragColor = vec4\(col, 1\.0\)/.test(frag));
ok('all holes use one fullscreen triangle',/workingSingularityViewport/.test(renderer)&&/setIndices\(\[0,1,2\]\)/.test(renderer));
console.log(pass+' passed, '+fail+' failed');process.exit(fail?1:0);
