import fs from 'fs';let pass=0,fail=0;const ok=(n,c)=>{if(c)pass++;else{fail++;console.log('FAIL: '+n);}};
const world=fs.readFileSync('src/bjs/worlds/BlackHoleWorld.ts','utf8');
const rend=fs.readFileSync('src/bjs/systems/HoleFieldRenderer.ts','utf8');
const sun=fs.readFileSync('src/bjs/shaders/SunShader.ts','utf8');
ok('all holes share the working material',rend.includes('WORKING_SINGULARITY_FRAG'));
ok('open-world disk radiance is calibrated',/diskBright',p\.diskBright\*\.099/.test(rend));
ok('open-world exposure is bounded',/exposure',\.72/.test(rend));
ok('the material includes filmic tone mapping',/filmic tonemap/.test(world));
ok('the material clamps before gamma output',/pow\(clamp\(col, 0\.0, 1\.0\)/.test(world));
ok('event-horizon alpha is opaque',/vec4\(col, 1\.0\)/.test(world));
ok('zero-height canvases use safe aspect',/safeAspect/.test(rend));
ok('a single triangle prevents diagonal seams',/setVerticesData\('position',\[-1,-1,0,3,-1,0,-1,3,0\]/.test(rend));
ok('the angular spike term is gone',!/pow\(abs\(cos\(ang \* 2\.0\)\), 22\.0\)/.test(sun));
ok('no cos-power starburst remains',!/star4|star6/.test(sun));
ok('sun glare stays isotropic',/ISOTROPIC RADIAL GAUSSIAN PROFILE/.test(sun));
ok('the core remains searing',/float core  = exp\(-r \* r \* 34\.0\)/.test(sun));
ok('the sun keeps blazing orange',/vec3\(1\.0, 0\.478, 0\.0\)/.test(sun));
ok('the sun keeps deep solar gold',/vec3\(1\.0, 0\.700, 0\.0\)/.test(sun));
console.log(pass+' passed, '+fail+' failed');process.exit(fail?1:0);
